// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN74miLWec9_vccSXoOrlpI7v2_9rKwVA',
    appId: '1:498034837678:web:fa5c97e90066c6d773453f',
    messagingSenderId: '498034837678',
    projectId: 'craveapp-b698b',
    authDomain: 'craveapp-b698b.firebaseapp.com',
    databaseURL: 'https://craveapp-b698b-default-rtdb.firebaseio.com',
    storageBucket: 'craveapp-b698b.appspot.com',
    measurementId: 'G-4EH1E2LB5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqIbYD0VnU9BxCjsdKCRnWmEb0K77wUsc',
    appId: '1:498034837678:android:3f0bd0324e4b268273453f',
    messagingSenderId: '498034837678',
    projectId: 'craveapp-b698b',
    databaseURL: 'https://craveapp-b698b-default-rtdb.firebaseio.com',
    storageBucket: 'craveapp-b698b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv13rwlEc4Y8HzVHaHQM_t3xuHvkd0Lpg',
    appId: '1:498034837678:ios:e79969944076444473453f',
    messagingSenderId: '498034837678',
    projectId: 'craveapp-b698b',
    databaseURL: 'https://craveapp-b698b-default-rtdb.firebaseio.com',
    storageBucket: 'craveapp-b698b.appspot.com',
    iosClientId: '498034837678-kcpd4kkkdn23lcj0e4u2jfphdl8auhvs.apps.googleusercontent.com',
    iosBundleId: 'com.cecs491app.craveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv13rwlEc4Y8HzVHaHQM_t3xuHvkd0Lpg',
    appId: '1:498034837678:ios:7458e039fd36244973453f',
    messagingSenderId: '498034837678',
    projectId: 'craveapp-b698b',
    databaseURL: 'https://craveapp-b698b-default-rtdb.firebaseio.com',
    storageBucket: 'craveapp-b698b.appspot.com',
    iosClientId: '498034837678-4d3tf5fu8f1mv3c1vhq8ific5gap7a36.apps.googleusercontent.com',
    iosBundleId: 'com.example.craveApp',
  );



}
